# metadata for this action
name: 'Intro to actions'
description: 'Greet new contributors when they create their first issue or open their first pull request'
author: 'GitHub'
branding:
  icon: 'award'
  color: 'yellow'

# 입력값
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  issue-message:
    description: 'Comment to post on an individual''s first issue'
  pr-message:
    description: 'Comment to post on an individual''s first pull request'

runs:
  # action execution environment
  using: 'docker'
  image: 'Dockerfile'

# 출력값
outputs:
  result:
    description: This is output